# More info at https://github.com/necojackarc/auto-request-review
reviewers:
  defaults:
    - cmwaters
    - evan-forbes
    - ninabarbakadze
    - rach-id
    - rootulp

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
